export { default as SignIn } from "components/SignIn/SignIn";
export { default as SignUp } from "components/SignUp/SignUp";
export { default as ThrowWork } from "components/ThorwWork/ThrowWork";
export { default as Header } from "components/Header/Header";
export { default as MainCarousel } from "components/Carousel/Main/MainCarousel";
export { default as MyCard } from "components/MyCard/MyCard";
export { default as MyModal } from "components/MyModal/MyModal";
export { default as TextAnimation } from "components/TextAnimation/TextAnimation";
export { default as Footer } from "components/Footer/Footer";
